# Dependencies
markdown:         redcarpet
#highlighter:      pygments
gems: [jekyll-paginate,redcarpet,jekyll-gist,glynn]

# Permalinks
permalink:        /:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:            Khalid Scratch Board
tagline:          ''
description:      'Spontaneously wrote, from me to you to others for everyone – khal.web.id'
url:              http://khalidadisendjaja.web.id
baseurl:          /

author:
  name:           'Khalid Adisendjaja'
  url:            https://twitter.com/khalidity

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

exclude:
  - package.json
  - node_modules
  - gulpfile.js

