baseURL: http://khal.web.id
disablePathToLower: true
languageCode: en-us
title: Khalid's Blog
seURL: "http://khal.web.id"
permalinks:
  post: /:year/:month/:day/:title/
params:
  description: "Spontaneously wrote, from me to you to others for everyone"
  AuthorName: "Khalid Adisendjaja"
  GitHubUser: "kh411d"
  SidebarRecentLimit: 5
disqusShortname: khalidity