baseURL: http://khal.web.id/
disablePathToLower: true
languageCode: en-us
title: Khalid's Blog
DefaultContentLanguage: "en"
enableInlineShortcodes: true
permalinks:
  post: /:year/:month/:day/:title/
params:
  description: "a coder who happen to be a spontaneous writer in a big pond who likes to write not in codes, talk in human and sense as a human"
  AuthorName: "Khalid Adisendjaja"
  GitHubUser: "kh411d"
  SidebarRecentLimit: 5
  cover: "/images/sidebar.jpg"
  author: "Khalid Adisendjaja"
  authorlocation: "Jakarta, Indonesia"
  authorwebsite: "http://khal.web.id"
  authorbio: "a #Coder with a bit #InfoJunkie, proud #Muslim and also #Indonesian"
  logo: "images/logo.jpeg"
  githubName: "kh411d"
  twitterName: "khalidity"
  linkedinName: "khalidadisendjaja"
  instagramName: "khalidity"
  email: "contact@khal.web.id"
  hideHUGOSupport: false
  #hjsStyle: "default"
  baseURL: "http://khal.web.id/"
  summaryLength: 30
disqusShortname: khal-web-id
theme: paper
enableEmoji: true
summaryLength: 30
googleAnalytics: "UA-8671044-1"
pygmentsUseClasses: true
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: emacs
    tabWidth: 4