baseURL: https://khal.web.id/
disablePathToLower: true
languageCode: en-us
title: Khalid's Blog
Author:
  name: Khalid Adisendjaja
  email: contact@khal.web.id
DefaultContentLanguage: "en"
enableInlineShortcodes: true
permalinks:
  post: /:year/:month/:day/:title/
params:
  description: "to code is to mess, to write is to keep"
  AuthorName: "Khalid Adisendjaja"
  GitHubUser: "kh411d"
  SidebarRecentLimit: 5
  cover: "/images/sidebar.jpg"
  author: "Khalid Adisendjaja"
  authorlocation: "Jakarta, Indonesia"
  authorwebsite: "https://khal.web.id"
  authorbio: "a #Coder with a bit #InfoJunkie, proud #Muslim and also #Indonesian"
  logo: "images/logo.jpeg"
  githubName: "kh411d"
  twitterName: "khalidity"
  linkedinName: "khalidadisendjaja"
  instagramName: ""
  eyeemName: "khalidity"
  email: "contact@khal.web.id"
  hideHUGOSupport: false
  #hjsStyle: "default"
  baseURL: "https://khal.web.id/"
  summaryLength: 70
#disqusShortname: khal-web-id
theme: paper
enableEmoji: true
#summaryLength: 70
googleAnalytics: "UA-8671044-1"
pygmentsUseClasses: true
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: emacs
    tabWidth: 4